services:
  agent:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["/entrypoints/agent_entrypoint.sh"]
    volumes:
      - ./results:/results
    networks:
      - ros_docker_reservoir_rossler

  edge:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["/entrypoints/edge_entrypoint.sh"]
    networks:
      - ros_docker_reservoir_rossler

networks:
  ros_docker_reservoir_rossler:
    name: ros_reservoir_rossler
